name: "Zhonghong VRF"
version: "0.3.5"
slug: "zhonghong_vrf"
description: "HTTP based Zhonghong vrf controller"
url: "https://github.com/donny2003/zhonghong_vrf"
#url: "https://github.com/xswxm/hassio-addons/tree/main/zhonghong_vrf"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
image https://github.com/donny2003/zhonghong_vrf/blob/master/icon.png
#image: xswxm/{arch}-addon-zhonghong_vrf
options:
  broker: "192.168.18.27"
  port: "1883"
  username: "pulo"
  password: "667788"
  gateway: "192.168.18.88"
schema:
  broker: str
  port: str
  username: str
  password: str
  gateway: str
